/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hacker-room-new.glb -T 
Files: hacker-room-new.glb [34.62MB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/hacker-room-new-transformed.glb [2.56MB] (93%)
*/

import { useGLTF, useTexture } from '@react-three/drei';

export function HackerRoom(props) {
  const { nodes, materials } = useGLTF('/models/hacker-room.glb');

  const monitortxt = useTexture('textures/desk/pink.jpg');
  const screenTxt = useTexture('textures/desk/screen.png');
  const table = useTexture('textures/desk/desk.png');
  const monitor= useTexture('textures/desk/black.png');
  const color1= useTexture('textures/desk/silver.png');
  const color2= useTexture('textures/desk/color2.png');
  const color3= useTexture('textures/desk/color3.png');
  const carpet= useTexture('textures/desk/carpet.jpg');
  const white= useTexture('textures/desk/table.png');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.screen_screens_0.geometry} material={materials.screens}>
        <meshMatcapMaterial map={screenTxt} />
      </mesh>
      <mesh geometry={nodes.screen_glass_glass_0.geometry} material={materials.glass} />
      <mesh geometry={nodes.table_table_mat_0_1.geometry} material={materials.table_mat} >
        <meshMatcapMaterial map={color1} />
      </mesh>
     
      <mesh geometry={nodes.table_table_mat_0_2.geometry} material={materials.computer_mat}>
        <meshMatcapMaterial map={color2} />
      </mesh>
      <mesh geometry={nodes.table_table_mat_0_3.geometry} material={materials.server_mat} >
        <meshMatcapMaterial map={color3} />
      </mesh>
      {/* <mesh geometry={nodes.table_table_mat_0_4.geometry} material={materials.vhsPlayer_mat} />
      <mesh geometry={nodes.table_table_mat_0_5.geometry} material={materials.stand_mat} /> */}
       
      {/* mouse pad ** */}
      <mesh geometry={nodes.table_table_mat_0_6.geometry} material={materials.mat_mat}>
        <meshMatcapMaterial map={color3} />
      </mesh> 

      <mesh geometry={nodes.table_table_mat_0_7.geometry} material={materials.arm_mat} />
    
      {/* <mesh geometry={nodes.table_table_mat_0_9.geometry} material={materials.cables_mat} /> */}
      
      {/* <mesh geometry={nodes.table_table_mat_0_11.geometry} material={materials.ground_mat} scale={.5}> 
         <meshMatcapMaterial map={carpet} />
    
      </mesh> */}
{/* keyboard */}
      
      
    </group>
  );
}

useGLTF.preload('/models/hacker-room.glb');