/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Joe (https://sketchfab.com/joeoregan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mouse-6f94cf357f3d42c5b37d8d0a25ecc0ee
Title: Mouse
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/mouse.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="bade1b88ecd242a0bb445d21dbd71fa9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="mesh" position={[0, 1.5, 0]} scale={[0.595, 1.205, 0.873]}>
                  <group name="mouse_button_side_left">
                    <mesh
                      name="mouse_button_side_left_lambert1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mouse_button_side_left_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group name="mouse_button_side_right">
                    <mesh
                      name="mouse_button_side_right_lambert1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mouse_button_side_right_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <group name="mouse_button_left">
                    <mesh
                      name="mouse_button_left_aiStandardSurface1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mouse_button_left_aiStandardSurface1_0.geometry}
                      material={materials.aiStandardSurface1}
                    />
                  </group>
                  <group name="mouse_button_right" position={[3.227, 0, 0]}>
                    <mesh
                      name="mouse_button_right_pasted__aiStandardSurface9_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mouse_button_right_pasted__aiStandardSurface9_0.geometry}
                      material={materials.pasted__aiStandardSurface9}
                    />
                  </group>
                  <group name="mouse_top">
                    <mesh
                      name="mouse_top_aiStandardSurface1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mouse_top_aiStandardSurface1_0.geometry}
                      material={materials.aiStandardSurface1}
                    />
                  </group>
                  <group name="mouse_middle">
                    <mesh
                      name="mouse_middle_aiStandardSurface6_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mouse_middle_aiStandardSurface6_0.geometry}
                      material={materials.aiStandardSurface6}
                    />
                  </group>
                  <group name="mouse_base">
                    <mesh
                      name="mouse_base_aiStandardSurface1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.mouse_base_aiStandardSurface1_0.geometry}
                      material={materials.aiStandardSurface1}
                    />
                    <group name="mouse_wheel">
                      <mesh
                        name="mouse_wheel_standardSurfaceMouse_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.mouse_wheel_standardSurfaceMouse_0.geometry}
                        material={materials.standardSurfaceMouse}
                      />
                    </group>
                    <group name="mouse_light">
                      <mesh
                        name="mouse_light_lambert1_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.mouse_light_lambert1_0.geometry}
                        material={materials.lambert1}
                      />
                      <group name="light_pCylinder1" />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/mouse.glb')
