/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: thelettervi (https://sketchfab.com/thelettervi)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/cat-mug-bcc6c5ecfa13476c98ee40ee968bd17f
Title: Cat Mug
*/


import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/cat_mug.glb')
  const { actions } = useAnimations(animations, group)
  const cat = useTexture('textures/desk/cat2.jpg')
  const coffee = useTexture('textures/desk/table.png')
  
  useEffect(() => {
    console.log(actions); 
    actions['Take 001'].timeScale = 4;
    actions['Take 001'].play();    
  }, [actions])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -5]} scale={0.24}>
          <group name="7ba9fd3396d64d27bbf8e0108519f4c4fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="cup" position={[0, 1.018, 0]}>
                  <group name="ceramic">
                    <mesh
                      name="ceramic_cat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.ceramic_cat_0.geometry}
                      material={materials.material}
                    >
                      <meshMatcapMaterial map={cat} />
                    </mesh>
                  </group>
                  <group name="liquid" scale={[1.064, 1, 1.064]}>
                    <mesh
                      name="liquid_phong1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.liquid_phong1_0.geometry}
                      material={materials.phong1}
                    >
                      <meshMatcapMaterial map={coffee} />
                    </mesh>
                  </group>
                </group>
                <group name="steam" position={[0, 4.166, 0]} scale={[0.518, 1, 1]} />
                <group
                  name="sine1Handle"
                  position={[0, 4.594, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={1.357}
                />
                <group name="steam2" position={[0, 4.166, 0]} scale={[0.518, 1, 1]}>
                  <mesh
                    name="0"
                    castShadow
                    receiveShadow
                    geometry={nodes['0'].geometry}
                    material={materials.lambert2}
                    material-transparent={true}
                    material-opacity={0.2}
                    morphTargetDictionary={nodes['0'].morphTargetDictionary}
                    morphTargetInfluences={nodes['0'].morphTargetInfluences}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cat_mug.glb')
